#!/usr/bin/env bash
# This script takes the domain and the subdomain, passes it to the dig command, to see what IP address it is pointing to.
if [ $# -eq 1 ]
then
    for i in 'www' 'lb-01' 'web-01' 'web-02'
    do
        concat="${i}.$1"
        dig "$concat" | grep -A1 'ANSWER SECTION:' | awk -v _sub=$i 'FNR==2 {print "The subdomain " _sub " is a " $4 " record and points to " $5}'
    done
fi
if [ $# -eq 2 ]
then
    concat="$2.$1"
    dig "$concat" | grep -A1 'ANSWER SECTION:' | awk -v _sub=$2 'FNR==2 {print "The subdomain " _sub " is a " $4 " record and points to " $5}'
fi