#!/usr/bin/env bash
# This script transfers a file from our client to a server.
args=("$@")
if [ "$#" -lt 3 ]
then
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
else
    scp -o StrictHostKeyChecking=no -i "${args[3]}" "${args[0]}" "${args[2]}"@"${args[1]}":~  
fi
