#!/usr/bin/env bash
# This script that install nginx, listening on port 80, the page that contains
# the string Holberton School and restarting nginx without systemctl.
sudo apt-get update
sudo apt-get install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo /etc/init.d/nginx restart
