#!/usr/bin/env bash
# This script configure your Nginx server so that
# '/redirect_me' is redirecting to another page.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
chmod 777 /etc/nginx/sities-availables/default
sudo sed -i "/server_name _;/ a \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=hDfWTuRFOTg permanent;" /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
