#!/usr/bin/env bash
# This script configure Nginx so that its HTTP response contains a custom header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
chmod 777 /etc/nginx/sities-availables/default
sudo sed -i "/server_name _;/ a \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=hDfWTuRFOTg permanent;" /etc/nginx/sites-available/default
sudo touch /usr/share/nginx/html/404.html
sudo chmod 777 /usr/share/nginx/html/404.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
sudo sed -i "/server_name _;/ a \\\terror_page 404 /404.html; location = /404.html {root /usr/share/nginx/html; internal; }" /etc/nginx/sites-available/default
sudo sed -i "/server_name _;/ a \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
