#!/usr/bin/env bash
# This script Install and configure HAproxy on your lb-01 server.
sudo apt-get update
sudo apt-get install haproxy -y
sudo chmod 777 /etc/default/haproxy
echo "ENABLED=1" >> /etc/default/haproxy
sudo chmod 777 /etc/haproxy/haproxy.cfg
echo -e "\nfrontend front\n\tbind *:80\\n\tmode http\n\tdefault_backend back" >> /etc/haproxy/haproxy.cfg
echo -e "\nbackend back\n\tmode http\n\tbalance roundrobin\n\tserver 3015-web-01 34.75.30.56:80\n\tserver 3015-web-02 54.234.166.77:80" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
