#!/usr/bin/env bash
# This script creates a file, displays To infinity and beyond indefinitely,
# displays I hate the kill command when receiving a SIGTERM signal, displays Y U no love me?!
# when receiving a SIGINT signal and deletes the file and terminates itself
# when receiving a SIGQUIT or SIGTERM signal.
file_created=/var/run/holbertonscript.pid
echo $$ > "$file_created"
function _signal_sigterm_sigquit () {
    echo "I hate the kill command"
    rm -rf "$file_created"
    exit
}
function _signal_sigint () {
    echo "Y U no love me?!"
}
while :
    do
        echo "To infinity and beyond"
        sleep 2
        trap _signal_sigterm_sigquit SIGTERM
        trap _signal_sigint SIGINT
    done