#!/usr/bin/env bash
# This script displays: To infinity and beyond indefinitely, With a sleep 2 in
# between each iteration and I am invincible!!! when receiving a SIGTERM signal.
function _signal () {
    echo "I am invincible!!!"
}
while :
    do
        echo "To infinity and beyond"
        sleep 2
        trap _signal SIGTERM
    done
