#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 time. In the 4th iteration, display bad luck and
# in the 8th iteration, display good luck.
i="1"
while [ $i -lt 11 ]
    do
        if [ "$i" -eq 4 ]
        then
            echo "bad luck"
        elif [ "$i" -eq 8 ]
        then
            echo "good luck"
        else
            echo "Holberton School"
        fi
        i=$((i+1))
    done
