#!/usr/bin/env bash
# This script is displaying "Holberton School" 20 time. In the 4th iteration display 4 and bad
# luck from China, in the 9th iteration display 9 and bad luck from Japan and in the and in the 9th
# iteration display 17 and bad luck from Italy.
i="1"
while [ $i -lt 21 ]
    do
        case $i in 
            4)
                echo "$i"
                echo "bad luck from China"
                ;;
            9)
                echo "$i"
                echo "bad luck from Japan"
                ;;
            17)
                echo "$i"
                echo "bad luck from Italy"
                ;;
            *)
                echo "$i"
        esac
        i=$((i+1))
    done
