#!/usr/bin/env bash
# This script create a user called nginx and running as nginx user
# nginx must be listening on all active IPs on port 8080
/etc/init.d/apache2 stop
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
chmod a+rwx /etc/nginx/nginx.conf
sudo -u nginx service nginx start
