#!/usr/bin/env bash
# This script make your fix short and sweet of point 1.
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i "s/80 default_server/8080 default_server/" /etc/nginx/sites-available/default
sudo -u nginx /etc/init.d/nginx start
